### PR TITLE
add a dash of our corporate design to the homepage

### PR DESCRIPTION
**Pull request by majewsky**
This branch is already way too big, time to have you all review it.

After struggling to find a suitable design for our homepage that incorporates the corporate design elements created in the last weeks and months, I had the idea to steal _cough_ learn from the design of our Twitter homepage. The result turns out aesthetically pleasing, at least to me.

The easiest way for you to check this out is probably by checking out the branch; only local assets are required. Apart from the visuals, I'd like comments on the markup. I hope I've used `<header>`, `<section>` et al correctly.

As a side note, I'm adding another webfont (FontAwesome) for icons, which is also under the SIL Open Font License, so we're clear from a licensing point of view.

### CODE REVIEW

**Comment by jklmnn** [comment]
+1

**Comment by horazont** [comment]
We could use SVG for our icon ([caniuse](http://caniuse.com/svg-html5) suggests that we can use it)

**Comment by majewsky** [comment]
Good point, will do. My mind has suffered in the days when I had to support MSIE 8. ;)

@horazont has also pointed out that using a CSS framework like YAML could help with adaptability to mobile screens. I have some basic adjustments for responsiveness in my working copy, and we can look into that tonight.

I consider YAML etc. out of scope for this pull request. The point is right now to align the website with our CD and our other media just enough, as a baseline for future design work.

**Comment by horazont** [comment]
+1 with YAML being out of scope, that can be fixed later. Not to mention that I hate mobiles ;)

**Pull request merged**
