### PR TITLE
Feature nowebfonts

### PR DESCRIPTION
**Pull request by s72785**
fixing #39 and supporting #38

Font-Awesome is unfortunately a webfont and webfonts are blocked by a sensitive configuration
besides that the project moves on to commercialize and slow down integration of e.g. diaspora symbol
and the whole webfont uses more bandwidth for just very few symbols used
so I propose to change towards css defined svg background-image for those buttons
- usabilty/compatibility
- no security flaw
- more flexible
- less get requests
- easy to extend for new svg logo/symbol used

SVG can be minified and converted to base64 data uri e.g. with help of
- http://www.svgminify.com/
- http://b64.io/

### CODE REVIEW

**Comment by s72785** [comment]
fixing #41

**Comment by s72785** [comment]
fixed #38 - feature complete, please review :)

**Comment by majewsky** [comment]
Looks good to me, but there's a lot of whitespace changes in there. Could you please get rid of these to make reviewing easier?

**Comment by s72785** [comment]
mh, sollte jetzt passen hoffe ich.

Wenn mal wieder Symbole aus Font-Awesome fehlen, habe die SVG von 4.4 mal hier nach forkt extrahiert: http://github.com/s72785/Font-Awesome-SVG-PNG - lässt sich auch leicht aktualisieren falls etwas neues kommt.

**Pull request merged**
